<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dateTime = now();
        DB::table('languages')->truncate();
        DB::table('languages')->insert([
            [
                'id' => 1,
                'language' => 'Afrikaans',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 2,
                'language' => 'Albanian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 3,
                'language' => 'Amharic',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 4,
                'language' => 'Arabic',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 5,
                'language' => 'Armenian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 6,
                'language' => 'Australian English',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 7,
                'language' => 'Austrian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 8,
                'language' => 'Avarian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 9,
                'language' => 'Azerbaijani',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 10,
                'language' => 'Basque',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 11,
                'language' => 'Belarusian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 12,
                'language' => 'Bengali',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 13,
                'language' => 'Berber',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 14,
                'language' => 'Bosnian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 15,
                'language' => 'Bulgarian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 16,
                'language' => 'Burmese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 17,
                'language' => 'CANS',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 18,
                'language' => 'Cantonese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 19,
                'language' => 'Catalan',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 20,
                'language' => 'Chavacano',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 21,
                'language' => 'Creole',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 22,
                'language' => 'Croatian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 23,
                'language' => 'Czech',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 24,
                'language' => 'Danish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 25,
                'language' => 'Dutch',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 26,
                'language' => 'English',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 27,
                'language' => 'Esperanto',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 28,
                'language' => 'Estonian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 29,
                'language' => 'Farsi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 30,
                'language' => 'Finnish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 31,
                'language' => 'French',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 32,
                'language' => 'Fukien',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 33,
                'language' => 'Galician',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 34,
                'language' => 'Georgian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 35,
                'language' => 'German',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 36,
                'language' => 'Ghanaian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 37,
                'language' => 'Greek',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 38,
                'language' => 'Gujarati',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 39,
                'language' => 'Haitian Creole',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 40,
                'language' => 'Hausa',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 41,
                'language' => 'Hebrew',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 42,
                'language' => 'Hindi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 43,
                'language' => 'Hmong',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 44,
                'language' => 'Hokkien',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 45,
                'language' => 'Hungarian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 46,
                'language' => 'Icelandic',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 47,
                'language' => 'Igbo',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 48,
                'language' => 'Indonesian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 49,
                'language' => 'Iranian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 50,
                'language' => 'Irish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 51,
                'language' => 'Italian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 52,
                'language' => 'Japanese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 53,
                'language' => 'KORS',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 54,
                'language' => 'Kannada',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 55,
                'language' => 'Khmer',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 56,
                'language' => 'Korean',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 57,
                'language' => 'Kyrgyz',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 58,
                'language' => 'Lao',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 59,
                'language' => 'Latin',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 60,
                'language' => 'Latvia',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 61,
                'language' => 'Lithuanian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 62,
                'language' => 'MANCAN',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 63,
                'language' => 'MANS',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 64,
                'language' => 'Macedonian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 65,
                'language' => 'Malay',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 66,
                'language' => 'Malayalam',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 67,
                'language' => 'Maltese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 68,
                'language' => 'Mandarin',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 69,
                'language' => 'Mandarin-Simplified',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 70,
                'language' => 'Mandarin-Traditional',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 71,
                'language' => 'Maori',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 72,
                'language' => 'Marathi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 73,
                'language' => 'Mongolian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 74,
                'language' => 'N/A',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 75,
                'language' => 'Nepali',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 76,
                'language' => 'Non-Bilingual',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 77,
                'language' => 'Norwegian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 78,
                'language' => 'Persian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 79,
                'language' => 'Pidgin',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 80,
                'language' => 'Polish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 81,
                'language' => 'Portuguese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 82,
                'language' => 'Punjabi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 83,
                'language' => 'Romanian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 84,
                'language' => 'Russian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 85,
                'language' => 'Sample',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 86,
                'language' => 'Serbian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 87,
                'language' => 'Shona',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 88,
                'language' => 'Shrilanka',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 89,
                'language' => 'Sinhala',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 90,
                'language' => 'Slovak',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 91,
                'language' => 'Slovenian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 92,
                'language' => 'Somali',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 93,
                'language' => 'Spanish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 94,
                'language' => 'Swahili',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 95,
                'language' => 'Swedish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 96,
                'language' => 'Swiss German',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 97,
                'language' => 'Taiwanese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 98,
                'language' => 'Tamil',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 99,
                'language' => 'Telugu',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 100,
                'language' => 'Tetun',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 101,
                'language' => 'Thai',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 102,
                'language' => 'Turkish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 103,
                'language' => 'Twi dialect',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 104,
                'language' => 'Ukrainian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 105,
                'language' => 'Urdu',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 106,
                'language' => 'Vietnamese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 107,
                'language' => 'Welsh',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 108,
                'language' => 'Yiddish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 109,
                'language' => 'Yoruba',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 110,
                'language' => 'Z-FRDutch',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 111,
                'language' => 'Z-FRGerm',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 112,
                'language' => 'Z-FRSpan',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 113,
                'language' => 'Z-FRarabic',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 114,
                'language' => 'Z-FR|Span|Germ',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 115,
                'language' => 'Z-FrenIta',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 116,
                'language' => 'Z-GerSpanish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 117,
                'language' => 'Z-GermIta',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 118,
                'language' => 'Z-GermLatin',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 119,
                'language' => 'Z-HiPortuguese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 120,
                'language' => 'Z-HiSpanish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 121,
                'language' => 'Z-HindiFrench',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 122,
                'language' => 'Z-HindiTamil',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 123,
                'language' => 'Z-HindiThai',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 124,
                'language' => 'Z-IndoMal',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 125,
                'language' => 'Z-IndoMan',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 126,
                'language' => 'Z-JapDutch',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 127,
                'language' => 'Z-JapHindi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 128,
                'language' => 'Z-JapIndo',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 129,
                'language' => 'Z-JapItalian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 130,
                'language' => 'Z-JapKor',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 131,
                'language' => 'Z-JapMan',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 132,
                'language' => 'Z-JapPortuguese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 133,
                'language' => 'Z-JapSinhala',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 134,
                'language' => 'Z-JapSpanish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 135,
                'language' => 'Z-JapSwedish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 136,
                'language' => 'Z-JapTamil',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 137,
                'language' => 'Z-JapTurkish',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 138,
                'language' => 'Z-JapViet',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 139,
                'language' => 'Z-Jap|Kor|Man',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 140,
                'language' => 'Z-KorMan',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 141,
                'language' => 'Z-Malay|ManCan',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 142,
                'language' => 'Z-ManArabic',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 143,
                'language' => 'Z-ManHindi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 144,
                'language' => 'Z-ManHungarian',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 145,
                'language' => 'Z-ManTamil',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 146,
                'language' => 'Z-ManThai',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 147,
                'language' => 'Z-ManUrdu',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 148,
                'language' => 'Z-Man|Malay',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 149,
                'language' => 'Z-Man|Vietnamese',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 150,
                'language' => 'Z-NepaleseThai',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 151,
                'language' => 'Z-RomIta',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 152,
                'language' => 'Z-RussKor',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 153,
                'language' => 'Z-SpanIta',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 154,
                'language' => 'Z-SpanPor',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 155,
                'language' => 'Z-SwedNor',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 156,
                'language' => 'Z-ThaiJap',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 157,
                'language' => 'Z-ThaiViet',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 158,
                'language' => 'Z-UrduPunjabi',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'id' => 159,
                'language' => 'Zulu',
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
        ]);
    }
}
