<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LicenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        DB::table('licenses')->truncate();
        DB::table('licenses')->insert([
            [
                'id' => 1,
                'name' => 'ACCA',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'AWS',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'BOSH Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Bar Passer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'CCDA (Design Associate)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'CCNA (Associate)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'CCNA (Security)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'CCNP (Professional)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'CEH Certified Ethical Hacker&quot;',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'CILS (B1)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'CILS (B2)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'CILS (C1)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'CILS (C2)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'CISCO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'COSH Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'Certified Accounting Technician (CAT)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'Certified Bookkeeper (CB)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'Certified Internal Auditor (CIA)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'Certified Learning Instructor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'name' => 'Certified Management Accountant(CMA)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'name' => 'Certified Master Trainer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Certified Professional Coder',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Certified Public Accountant (CPA)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'Certified Sales Professional',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'Chartered Financial Analyst (CFA)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Chartered Institute of Personnel Development',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'name' => 'Citrix Certified Administrator',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Citrix Certified Enterprise Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'Civil Service Passer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'CompTIA',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'DELE A1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'name' => 'DELE A2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'name' => 'DELE B1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'name' => 'DELE B2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'name' => 'DELE C1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'name' => 'DELE C2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'name' => 'DOLE Accreditation',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'name' => 'Driver\'s License',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'name' => 'EPS TOPIK Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'name' => 'HSK 1 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'name' => 'HSK 2 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'name' => 'HSK 3 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'name' => 'HSK 4 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'name' => 'HSK 5 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'name' => 'HSK 6 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'name' => 'ISO Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'name' => 'ISO14001/9001',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'name' => 'JLPT N1 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'name' => 'JLPT N2 certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'name' => 'JLPT N3 certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'name' => 'JLPT N4 certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'name' => 'JLPT N5 certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'name' => 'JPEPA member',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'name' => 'LAWYER',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'name' => 'LET Passer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'name' => 'Licensed Customs Broker',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'name' => 'Licensed Geologist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'name' => 'Licensed Medical Doctor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'name' => 'Licensed Nutritionist - Dietitian',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'name' => 'Licensed Physical Therapist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'name' => 'Licensed Real Estate Broker',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'name' => 'MCP (Microsoft Certified Professional)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'name' => 'Microsoft Certified IT Professional',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'name' => 'Microsoft Certified MCSA/MCSE',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'name' => 'Microsoft Certified Technology Specialist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'name' => 'N/A',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'name' => 'OHSAS18001',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'name' => 'OSD Certificate A1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'name' => 'OSD Certificate A2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'name' => 'OSD Certificate B1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'name' => 'OSD Certificate B2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'name' => 'OSHA Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'name' => 'Professional Electrical Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'name' => 'Professional Mechanical Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'name' => 'Professional SAP ERP Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'name' => 'Registered Aeronautical Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'name' => 'Registered Architect',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'name' => 'Registered Chemical Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'name' => 'Registered Civil Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'name' => 'Registered Cost Accountant (RCA)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'name' => 'Registered Criminology',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'name' => 'Registered Electrical Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'name' => 'Registered Electronics Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'name' => 'Registered Electronics Technician',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'name' => 'Registered Interior Designer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'name' => 'Registered Librarian',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'name' => 'Registered Master Plumber',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'name' => 'Registered Master electrician',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'name' => 'Registered Mechanical Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'name' => 'Registered Medical Technologist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'name' => 'Registered Midwife',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'name' => 'Registered Nurse',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'name' => 'Registered Pharmacist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'name' => 'Registered Psychometrician',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'name' => 'Registered Radiologic Technology',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'name' => 'Registered Sanitary Engineer',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'name' => 'Six Sigma Black Belt Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'name' => 'Six Sigma Green Belt Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'name' => 'Six Sigma Master Black Belt Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'name' => 'Six Sigma White Belt Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'name' => 'Six Sigma Yellow Belt Certification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'name' => 'TELC A1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'name' => 'TELC A2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'name' => 'TELC B1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'name' => 'TELC B2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'name' => 'TELC C1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 107,
                'name' => 'TELC C2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 108,
                'name' => 'TOEIC Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 109,
                'name' => 'TOPIK I Level 1 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 110,
                'name' => 'TOPIK I Level 2 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 111,
                'name' => 'TOPIK II Level 3 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 112,
                'name' => 'TOPIK II Level 4 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 113,
                'name' => 'TOPIK II Level 5 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 114,
                'name' => 'TOPIK II Level 6 Certificate',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 115,
                'name' => 'Trainers Methodology Level 2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 116,
                'name' => 'Trainers Methodology Level I',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 117,
                'name' => 'US NCLEX-RN',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 118,
                'name' => 'US Registered Nurse',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 119,
                'name' => 'VMware Certified Design Expert 5',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 120,
                'name' => 'VMware Certified Professional',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 121,
                'name' => 'VMware Certified Spring Professional',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
