<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        DB::table('locations')->truncate();
        DB::table('locations')->insert([
            [
                'id' => 1,
                'location' => 'Philippines',
                'type' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'location' => 'Abroad',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'location' => 'Africa',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'location' => 'Algeria',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'location' => 'America',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'location' => 'Argentina',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'location' => 'Armenia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'location' => 'Australia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'location' => 'Austria',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'location' => 'Azerbaijan',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'location' => 'Bahrain',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'location' => 'Bangladesh',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'location' => 'Belarus',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'location' => 'Belgium',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'location' => 'Brazil',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'location' => 'Brunei',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'location' => 'Bulgaria',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'location' => 'Cambodia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'location' => 'Cameroon',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'location' => 'Canada',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'location' => 'Chile',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'location' => 'China',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'location' => 'Colombia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'location' => 'Congo',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'location' => 'Costa Rica',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'location' => 'Croatia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'location' => 'Cuba',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'location' => 'Curaçao',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'location' => 'Czech Republic',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'location' => 'Denmark',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'location' => 'Dominican Republic',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'location' => 'Dubai',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'location' => 'Egypt',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'location' => 'Estonia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'location' => 'Ethiopia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'location' => 'Finland',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'location' => 'France',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'location' => 'Gabon',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'location' => 'Georgia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'location' => 'Germany',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'location' => 'Gibraltar',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'location' => 'Greece',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'location' => 'Guam',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'location' => 'Guatemala',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'location' => 'Honduras',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'location' => 'Hongkong',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'location' => 'Hungary',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'location' => 'India',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'location' => 'Indonesia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'location' => 'Iran',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'location' => 'Ireland',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'location' => 'Israel',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'location' => 'Italy',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'location' => 'Ivory Coast',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'location' => 'Japan',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'location' => 'Jordan',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'location' => 'Kenya',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'location' => 'Korea',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'location' => 'Kuwait',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'location' => 'Kyrgyzstan',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'location' => 'Latvia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'location' => 'Lebanon',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'location' => 'Lithuania',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'location' => 'London',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'location' => 'Macau',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'location' => 'Madagascar',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'location' => 'Malaysia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'location' => 'Maldives',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'location' => 'Malta',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'location' => 'Mauritius',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'location' => 'Mexico',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'location' => 'Mongolia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'location' => 'Morocco',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'location' => 'Mozambique',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'location' => 'Myanmar',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'location' => 'N/A',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'location' => 'Nepal',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'location' => 'Netherlands',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'location' => 'New Zealand',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'location' => 'Nicaragua',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'location' => 'Norway',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'location' => 'Oman',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'location' => 'Pakistan',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'location' => 'Paraguay',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'location' => 'Peru',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'location' => 'Poland',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'location' => 'Portugal',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'location' => 'Puerto Rico',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'location' => 'Qatar',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'location' => 'Romania',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'location' => 'Russia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'location' => 'Saudi Arabia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'location' => 'Serbia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'location' => 'Singapore',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'location' => 'Slovakia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'location' => 'Slovenia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'location' => 'Spain',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'location' => 'Sri Lanka',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'location' => 'Sweden',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'location' => 'Switzerland',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'location' => 'Syria',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'location' => 'Taiwan',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'location' => 'Tanzania',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'location' => 'Thailand',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'location' => 'Togo',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'location' => 'Tunisia',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 107,
                'location' => 'Turkey',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 108,
                'location' => 'UAE',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 109,
                'location' => 'UK',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 110,
                'location' => 'Ukraine',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 111,
                'location' => 'United States (USA)',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 112,
                'location' => 'Uruguay',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 113,
                'location' => 'Venezuela',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 114,
                'location' => 'Vietnam',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 115,
                'location' => 'Zimbabwe',
                'type' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
