<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nationalities')->truncate();
        DB::table('nationalities')->insert([
            [
                'id' => 1,
                'nationality' => 'African',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nationality' => 'Albanian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nationality' => 'Algerian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nationality' => 'American',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nationality' => 'Andorran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nationality' => 'Angolan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nationality' => 'Arabic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nationality' => 'Argentinian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'nationality' => 'Armenian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'nationality' => 'Australian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'nationality' => 'Austrian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'nationality' => 'Azerbaijan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'nationality' => 'Azerbaijani',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'nationality' => 'BELARUS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'nationality' => 'Bahraini',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'nationality' => 'Bangladesh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'nationality' => 'Belgian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'nationality' => 'Beninese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'nationality' => 'Bolivian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'nationality' => 'Brazilian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'nationality' => 'British',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'nationality' => 'Brunei',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'nationality' => 'Bulgarian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'nationality' => 'Burundi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'nationality' => 'Cambodian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'nationality' => 'Cameroonian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'nationality' => 'Canadian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'nationality' => 'Chadian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'nationality' => 'Chilean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'nationality' => 'Chinese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'nationality' => 'Colombian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'nationality' => 'Congolese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'nationality' => 'Costarican',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'nationality' => 'Croatian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'nationality' => 'Cuban',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'nationality' => 'Czech',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'nationality' => 'Danish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'nationality' => 'Djiboutian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'nationality' => 'Dominican',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'nationality' => 'Dutch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'nationality' => 'Ecuadorian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'nationality' => 'Egyptian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'nationality' => 'Eritrean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'nationality' => 'Estonian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'nationality' => 'Ethiopian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'nationality' => 'Filipino',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'nationality' => 'Finnish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'nationality' => 'French',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'nationality' => 'Gabonese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'nationality' => 'Georgian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'nationality' => 'German',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'nationality' => 'Ghanaian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'nationality' => 'Greek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'nationality' => 'Guatemalan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'nationality' => 'Guinean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'nationality' => 'Haitian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'nationality' => 'Honduran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'nationality' => 'Hondurans',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'nationality' => 'Hong Kong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'nationality' => 'Hungarian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'nationality' => 'Icelandic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'nationality' => 'Indian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'nationality' => 'Indonesian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'nationality' => 'Iranian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'nationality' => 'Iraqi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'nationality' => 'Irish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'nationality' => 'Israeli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'nationality' => 'Italian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'nationality' => 'Ivorian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'nationality' => 'Jamaican',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'nationality' => 'Japanese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'nationality' => 'Jordanian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'nationality' => 'Kazakh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'nationality' => 'Kenyan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'nationality' => 'Korean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'nationality' => 'Kuwaiti',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'nationality' => 'Kyrgyzstan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'nationality' => 'Lao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'nationality' => 'Latvian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'nationality' => 'Lebanese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'nationality' => 'Liberian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'nationality' => 'Libya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'nationality' => 'Lithuanian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'nationality' => 'Luxembourg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'nationality' => 'Malagasy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'nationality' => 'Malaysian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'nationality' => 'Malian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'nationality' => 'Mauritius',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'nationality' => 'Mexican',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'nationality' => 'Moldovan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'nationality' => 'Mongolian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'nationality' => 'Moroccan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'nationality' => 'Mozambique',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'nationality' => 'Myanmar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'nationality' => 'N/A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'nationality' => 'Nepalese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'nationality' => 'New Zealander',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'nationality' => 'Nicaraguan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'nationality' => 'Nigerian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'nationality' => 'Norwegian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'nationality' => 'Omani',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'nationality' => 'Pakistani',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'nationality' => 'Palestinian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'nationality' => 'Panamanian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'nationality' => 'Papua New Guinean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'nationality' => 'Paraguayan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'nationality' => 'Persian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'nationality' => 'Peruvian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'nationality' => 'Polish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'nationality' => 'Portuguese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'nationality' => 'Puerto Rican',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'nationality' => 'Romanian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'nationality' => 'Russian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'nationality' => 'Rwandese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'nationality' => 'Salvadorian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'nationality' => 'Senegalese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'nationality' => 'Serbian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'nationality' => 'Seychelles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'nationality' => 'Shrilanka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'nationality' => 'Singaporean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'nationality' => 'Slovak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'nationality' => 'Slovenian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'nationality' => 'Somalia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'nationality' => 'Spanish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'nationality' => 'Sri Lankan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'nationality' => 'Sudanese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'nationality' => 'Swedish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'nationality' => 'Swiss',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 129,
                'nationality' => 'Syrian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 130,
                'nationality' => 'Taiwanese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 131,
                'nationality' => 'Tajikistan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 132,
                'nationality' => 'Tanzanian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 133,
                'nationality' => 'Thai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 134,
                'nationality' => 'Timorese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'nationality' => 'Togolese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'nationality' => 'Tunisian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'nationality' => 'Turkish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'nationality' => 'Ugandan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'nationality' => 'Ukrainian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'nationality' => 'Uruguayan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'nationality' => 'Uzbekistan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 142,
                'nationality' => 'Venezuela',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'nationality' => 'Vietnamese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 144,
                'nationality' => 'Yemeni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'nationality' => 'Zimbabwean',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
