<?php

namespace App\Enums;

enum JobSeekerUniversityMajor: int
{
    case Accounting = 1;
    case Administrative = 2;
    case Advertising = 3;
    case Aeronautics = 4;
    case Agriculture = 5;
    case AircraftMaintenanceTechnology = 6;
    case Anatomy = 7;
    case Architecture = 8;
    case Arts = 9;
    case Astronomy = 10;
    case Auditing = 11;
    case Automotive = 12;
    case BankingAndFinance = 13;
    case Biology = 14;
    case Broadcasting = 15;
    case BusinessAdministrationAndManagement = 16;
    case Chemistry = 17;
    case Commerce = 18;
    case Communications = 19;
    case ComputerScience = 20;
    case ConstructionCostManagement = 21;
    case ConsularAndDiplomaticAffairs = 22;
    case Cosmetology = 23;
    case CreativeWriting = 24;
    case Criminology = 25;
    case CustomsAdministration = 26;
    case Dentistry = 27;
    case Design = 28;
    case Drafting = 29;
    case Economics = 30;
    case Education = 31;
    case Electronics = 32;
    case Engineering = 33;
    case EnglishMajor = 34;
    case Entrepreneurship = 35;
    case EuropeanOrAsianLanguages = 36;
    case Export = 37;
    case Fashion = 38;
    case Financial = 39;
    case FineArts = 40;
    case FoodTechnology = 41;
    case Geography = 42;
    case Geology = 43;
    case History = 44;
    case HotelStudies = 45;
    case HotelAndRestaurantManagement = 46;
    case HumanResource = 47;
    case IndustrialManagement = 48;
    case InformationTechnology = 49;
    case InfrastructureManagementSystem = 50;
    case InteriorDesign = 51;
    case InternationalStudies = 52;
    case Journalism = 53;
    case Law = 54;
    case LegalManagement = 55;
    case LibraryAndInformationScience = 56;
    case Linguistics = 57;
    case Literature = 58;
    case Logistics = 59;
    case Marine = 60;
    case MarketingManagement = 61;
    case MassCommunications = 62;
    case Mathematics = 63;
    case Mechanic = 64;
    case Mechanics = 65;
    case MedTech = 66;
    case Medicine = 67;
    case Military = 68;
    case ModernFrenchLetters = 69;
    case Multimedia = 70;
    case Music = 71;
    case NotCollegeGraduate = 72;
    case Nursing = 73;
    case NutritionFood = 74;
    case Pharmacy = 75;
    case Philosophy = 76;
    case PhysicalTherapy = 77;
    case Politics = 78;
    case Psychology = 79;
    case PublicRelations = 80;
    case Radiology = 81;
    case RealEstateManagement = 82;
    case Sciences = 83;
    case SocialWork = 84;
    case Sociology = 85;
    case Sports = 86;
    case StatisticsAndResearch = 87;
    case Taxation = 88;
    case Technician = 89;
    case Theology = 90;
    case Tourism = 91;
    case Trading = 92;

    /**
     * Get text equivalent
     *
     * @return string
     */
    public function text()
    {
        return match ($this) {
            self::Accounting => 'Accounting',
            self::Administrative => 'Administrative',
            self::Advertising => 'Advertising',
            self::Aeronautics => 'Aeronautics',
            self::Agriculture => 'Agriculture',
            self::AircraftMaintenanceTechnology => 'Aircraft Maintenance Technology',
            self::Anatomy => 'Anatomy',
            self::Architecture => 'Architecture',
            self::Arts => 'Arts',
            self::Astronomy => 'Astronomy',
            self::Auditing => 'Auditing',
            self::Automotive => 'Automotive',
            self::BankingAndFinance => 'Banking and Finance',
            self::Biology => 'Biology',
            self::Broadcasting => 'Broadcasting',
            self::BusinessAdministrationAndManagement => 'Business Administration and Management',
            self::Chemistry => 'Chemistry',
            self::Commerce => 'Commerce',
            self::Communications => 'Communications',
            self::ComputerScience => 'Computer Science',
            self::ConstructionCostManagement => 'Construction Cost Management',
            self::ConsularAndDiplomaticAffairs => 'Consular and Diplomatic Affairs',
            self::Cosmetology => 'Cosmetology',
            self::CreativeWriting => 'Creative Writing',
            self::Criminology => 'Criminology',
            self::CustomsAdministration => 'Customs Administration',
            self::Dentistry => 'Dentistry',
            self::Design => 'Design',
            self::Drafting => 'Drafting',
            self::Economics => 'Economics',
            self::Education => 'Education',
            self::Electronics => 'Electronics',
            self::Engineering => 'Engineering',
            self::EnglishMajor => 'English Major',
            self::Entrepreneurship => 'Entrepreneurship',
            self::EuropeanOrAsianLanguages => 'European or Asian Languages',
            self::Export => 'Export',
            self::Fashion => 'Fashion',
            self::Financial => 'Financial',
            self::FineArts => 'Fine Arts',
            self::FoodTechnology => 'Food Technology',
            self::Geography => 'Geography',
            self::Geology => 'Geology',
            self::History => 'History',
            self::HotelStudies => 'Hotel Studies',
            self::HotelAndRestaurantManagement => 'Hotel and Restaurant Management',
            self::HumanResource => 'Human Resource',
            self::IndustrialManagement => 'Industrial Management',
            self::InformationTechnology => 'Information Technology',
            self::InfrastructureManagementSystem => 'Infrastructure Management System',
            self::InteriorDesign => 'Interior Design',
            self::InternationalStudies => 'International Studies',
            self::Journalism => 'Journalism',
            self::Law => 'Law',
            self::LegalManagement => 'Legal Management',
            self::LibraryAndInformationScience => 'Library and Information Science',
            self::Linguistics => 'Linguistics',
            self::Literature => 'Literature',
            self::Logistics => 'Logistics',
            self::Marine => 'Marine',
            self::MarketingManagement => 'Marketing Management',
            self::MassCommunications => 'Mass Communications',
            self::Mathematics => 'Mathematics',
            self::Mechanic => 'Mechanic',
            self::Mechanics => 'Mechanics',
            self::MedTech => 'Med Tech',
            self::Medicine => 'Medicine',
            self::Military => 'Military',
            self::ModernFrenchLetters => 'Modern French Letters',
            self::Multimedia => 'Multimedia',
            self::Music => 'Music',
            self::NotCollegeGraduate => 'Not College Graduate',
            self::Nursing => 'Nursing',
            self::NutritionFood => 'Nutrition Food',
            self::Pharmacy => 'Pharmacy',
            self::Philosophy => 'Philosophy',
            self::PhysicalTherapy => 'PhysicalTherapy',
            self::Politics => 'Politics',
            self::Psychology => 'Psychology',
            self::PublicRelations => 'Public Relations',
            self::Radiology => 'Radiology',
            self::RealEstateManagement => 'Real Estate Management',
            self::Sciences => 'Sciences',
            self::SocialWork => 'Social Work',
            self::Sociology => 'Sociology',
            self::Sports => 'Sports',
            self::StatisticsAndResearch => 'Statistics and Research',
            self::Taxation => 'Taxation',
            self::Technician => 'Technician',
            self::Theology => 'Theology',
            self::Tourism => 'Tourism',
            self::Trading => 'Trading',
        };
    }
}
